### ISSUE TITLE
Add `toHaveUrlContaining` and `toHaveTitleContaining` matcher

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/expect-webdriverio#103]
Since we already have `toHaveTextContaining` it would be nice to also have such a matcher for urls. Given that we have `toHaveText` and `toHaveTextContaining` we should follow this pattern for `toHaveTitle` and `toHaveUrl` as aliases to e.g. `toHaveTitle("foobar", { containing: true })`.

**Comment by mathew-jithin** [comment]
Would like to work on this!

I think it should be in the same format as mentioned and already present in the repo?

**Comment by christian-bromann** [comment]
> I think it should be in the same format as mentioned and already present in the repo?

What do you mean by that?

**Comment by mathew-jithin** [comment]
@christian-bromann Actually I had a bit of doubt on the detailing on this change.

We need the functionality to be similar to the existing ones, like **toHaveText** and **toHaveTextContaining** right?

**Comment by mgrybyk** [comment]
@mathew-jithin take a look how existing *Containing are implemented. It should be just couple lines of code.
Please don't forget to add it to types definition file

**Comment by mathew-jithin** [comment]
@mgrybyk Sure. Thanks a lot!

**Comment by mathew-jithin** [comment]
@christian-bromann @mgrybyk Added a pull here: https://github.com/webdriverio/expect-webdriverio/pull/104 Have a few doubts. Adding the same there too.

**Comment by christian-bromann** [comment]
Awesome! Let's continue convo there.
