### ISSUE TITLE
Expose utility methods to enable external contribution of additional custom matchers.

### ISSUE THREAD

**Issue by sdedios** [webdriverio/expect-webdriverio#105]
I have a couple of matchers that I've already created for the Chai version of webdriver.io expects that I'd like to move over to the Jest-style matchers as I port to this framework.  The problem is that some of them might not make sense to be part of this core library and over time a monolithic package probably isn't the best idea anyways.

Would it be possible to expose a some of the existing custom methods and / or a new method to enable some extensibility?  Specifically, I'd be looking to at least get the core `src/utils` methods (e.g. `executeCommandBe ` and its dependencies).

The first method I'd like to swap in looks like this:

```javascript
// check the style (supports type validation of keys in Typescript)
expect(label).toHaveStyle({
    "font-family": "Faktum",
    "font-size": "26px",
    color: "#000" // handles "black", "#000000", "rgb(0, 0, 0)", and "rgba(0, 0, 0, 1)"
});
```

**Comment by christian-bromann** [comment]
@sdedios this makes totally sense. Feel free to provide a PR for this. 

> ```js
> expect(label).toHaveStyle({
> ```

What additional matchers do you already have. I am sure some of them are very useful to others too and could be added to the core lib. What do you think?

**Comment by mgrybyk** [comment]
@sdedios can you share the matchers you have so that we can improve matchers?

Regarding your question, the methods you've mentioned are exported and can be imported.

Let me know if you have any issues with that
