### ISSUE TITLE
Export `matchers` object

### ISSUE THREAD

**Issue by sidferreira** [webdriverio/expect-webdriverio#1120]
I'm working on a jest integration to WDIO.
One current limitation is how `expect-webdriverio` is fixed with the `extend` library.

If `expect-webdriverio` exports `matchers`, I can adequately patch jest and offer a seamless experience with it.

https://github.com/webdriverio/expect-webdriverio/blob/main/src/index.ts#L3-L6

```
import _matchers from './matchers.js'
import { DEFAULT_OPTIONS } from './constants.js'

export const matchers = _matchers;
```

**Comment by christian-bromann** [comment]
> I'm working on a jest integration to WDIO.

Can you share more about this? Why don't you just overwrite the Jest expect function or do:

```ts
import { expect as wdioExpect } from 'expect-webdriverio'
```

?

**Comment by sidferreira** [comment]
@christian-bromann TBH, I was so tired when I finished working that I failed to notice that both use the same base library!
