### ISSUE TITLE
Argument error message argument for `toBeDisplayed()` 

### ISSUE THREAD

**Issue by ccheung0926** [webdriverio/expect-webdriverio#1129]
Hi all,
My team recently want to include the standard for adding an argument for displaying custom error message inside `toBeDisplayed()` function. However, I tested the error messaging and it doesn't display in the terminal. Anyone knows how the optional argument works?

**Comment by christian-bromann** [comment]
Thanks for reporting!

Providing custom error messages is currently not support but would be nice to have. 

Any contributions that would implement this are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by erwinheitzman** [comment]
Works with the latest version
