### ISSUE TITLE
toHaveProperty conflicts with original Expect assertion

### ISSUE THREAD

**Issue by klamping** [webdriverio/expect-webdriverio#113]
`toHaveProperty` exists in both this library and the core ExpectJS package:
https://webdriver.io/docs/api/expect.html#tohaveproperty
https://jestjs.io/docs/en/expect#tohavepropertykeypath-value

This means you can't use the core ExpectJS assertion, because the WDIO one in this package overwrites it. 

Not really sure on a good solution. Maybe add a check in the custom matcher to see if it's an Object, and if so, use the Expect version. I'm not crazy about have two functions of the same name serve different purposes though... Maybe change the name of this matcher to `toHaveHtmlProperty` or `toHaveElementProperty`?

**Comment by mgrybyk** [comment]
We can save builtin matchers before overwriting them similar to what puppeteer guys did https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer/src/index.js#L89

**Comment by mgrybyk** [comment]
I'd rename `toHaveProperty` to what @klamping suggested:
- `toHaveHtmlProperty`
- `toHaveElementProperty`
- `toHaveNodeProperty`

Same issue with `toHaveClass` in jasmine https://jasmine.github.io/api/edge/matchers
Do you have any naming suggestions? I guess `toHaveElementClass` might work

The point why I'd go with renaming is that we have to deal with types as well. Taking into account overall complexity I'm not sure if it worth working on matchers overloading support.

**Comment by christian-bromann** [comment]
I would vote to rename to `toHaveElementProperty` and `toHaveElementClass`.

I am a bit afraid that this could break tests if we just release it as minor/patch in WebdriverIO. On the other side I don't feel like such a chance should trigger a major WebdriverIO release and confuse people. Any suggestions?

**Comment by mgrybyk** [comment]
We can rename these two and leave existing ones for 3 months or so, and also print deprecated message to force users using new renamed methods.
Additionally Id like to have some test to prevent similar situation in future

**Comment by christian-bromann** [comment]
Yes to both 👍

**Comment by mgrybyk** [comment]
Should be fixed with the PR
