### ISSUE TITLE
Typyings don't include jest matchers

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/expect-webdriverio#1145]
v 4.2.2

```ts
import { expect } from '@wdio/globals';
expect(true).toBe(false) // Argument of type 'boolean' is not assignable to parameter of type 'ExpectType'.
```

_tsconfig.json_
```json
"@wdio/globals/types",
"@wdio/cucumber-framework",
"expect-webdriverio",
"expect-webdriverio/jest",
"devtools"
```

**Comment by christian-bromann** [comment]
Pushed a fix that hopefully will resolve the issue. Will trigger a patch release now, let me know if it works.

**Comment by nextlevelbeard** [comment]
Fixed!

**Comment by nextlevelbeard** [comment]
@christian-bromann I may have spoken too soon as I am seeing the same behavior again today. Even after reinstalling dependencies.

Adding
```ts
import "expect-webdriverio"
```
seems to make the errors disappear.
Is there a change needed in the `@wdio/globals` package, perhaps?

**Comment by christian-bromann** [comment]
@nextlevelbeard can you provide a minimal reproducible example? I haven't been able to reproduce this.

**Comment by erwinheitzman** [comment]
@nextlevelbeard can we close this?
