### ISSUE TITLE
Implement support for snapshot testing

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/expect-webdriverio#1383]
We would like to have the ability for snapshot tests for general objects as well as for elements directly, e.g.:

```ts
// snapshot css object
expect(await browser.getCSSProperty('color')).toMatchSnapshot()
// snapshot elements directly
await expect(elem).toMatchElementSnapshot()
```

@AnthonyQuy already made an attempt on this in https://github.com/webdriverio/expect-webdriverio/pull/1375 which we had to rollback due to the following reason: we have to support running the snapshot comparisons in Node as well as in the browser environment. That means that loading the snapshot has to happen in the Node.js environment. One way to go about this is to have the matcher send events to the browser runner when in the browser or load the snapshot data into the browser.

cc @AnthonyQuy

**Comment by AnthonyQuy** [comment]
<img width="528" alt="image" src="https://github.com/webdriverio/expect-webdriverio/assets/19924396/e5426182-8c3c-44b2-b23c-f36da7ac3a34">

I just tried this in the test project seem working fine. Could you help provide more info on the browser environment issue...

**Comment by AnthonyQuy** [comment]
Noted with thanks @christian-bromann  I'm checking this and might take sometime to get more familiar on how the browser running test work...

**Comment by christian-bromann** [comment]
Landed in https://github.com/webdriverio/expect-webdriverio/pull/1426
