### ISSUE TITLE
Move into WebdiverIO

### ISSUE THREAD

**Issue by marklagendijk** [webdriverio/expect-webdriverio#150]
I think this module is must-have for writing nice web tests with WebdriverIO.
I stumbled upon this module when I read the release notes for WebdriverIO 6, and otherwise wouldn't have known about it.

Is there a specific reason why this was made as a separate module, instead of being bundled directly in WebdriverIO? Are you planning on bundling it with WebdriverIO in the future?

I believe that bundling this module directly into WebdriverIO would be one of the improvements that would help making with making it easier to write non-flaky tests with WebdriverIO, out-of-the-box.

Slightly related, [my isssue on WebdriverIO](https://github.com/webdriverio/webdriverio/issues/5732)

**Comment by klamping** [comment]
Starting in WebdriverIO V6, this package comes bundled in the main install. If you're using the test runner, you don't need to do anything else to use this package :)

**Comment by marklagendijk** [comment]
Awesome! I didn't know that. I see that it is even included properly in the [documentation](https://webdriver.io/docs/api/expect.html)
