### ISSUE TITLE
toHaveElementClass

### ISSUE THREAD

**Issue by muhserks** [webdriverio/expect-webdriverio#1505]
I am not sure if this is an issue or intended. So please forgive me if I am wrong ...

But toHaveElementClass+expect.stringContaining behaves different compared to toHaveElementClassContaining. Also toHaveElementClass gives a weird error message when passing multiple classes.

Lets say given is this div:
`<div id="d1" class="clickable step">test</div>`

Following works:
```
await expect(div).toHaveElementClass('clickable');
await expect(div).toHaveElementClass('step');
await expect(div).toHaveElementClass(expect.stringContaining('clickable'));
await expect(div).toHaveElementClass(expect.stringContaining('step'));
await expect(div).toHaveElementClassContaining('clickable step');
```

Following does not work:

`await expect(div).toHaveElementClass('clickable step');`
Result:
```
[chrome 122.0.6261.128 windows #0-0] Expect $(`//div[@id="d1"]`) to have class

Expected: "clickable step"
Received: serializes to the same string
[chrome 122.0.6261.128 windows #0-0] Error: Expect $(`//div[@id="d1"]`) to have class
[chrome 122.0.6261.128 windows #0-0]
[chrome 122.0.6261.128 windows #0-0] Expected: "clickable step"
[chrome 122.0.6261.128 windows #0-0] Received: serializes to the same string
[chrome 122.0.6261.128 windows #0-0]     at Context.<anonymous> (file:///C:/work/wdio/test/specs/test.e2e.ts:15:27)
[chrome 122.0.6261.128 windows #0-0]
[chrome 122.0.6261.128 windows #0-0] 2) Test Multiplice classes 2
[chrome 122.0.6261.128 windows #0-0] Expect $(`//div[@id="d1"]`) to have class
```

`await expect(div).toHaveElementClass(expect.stringContaining('clickable step'));`
Result:
```
Expected: StringContaining "clickable step"
Received: "clickable step"
[chrome 122.0.6261.128 windows #0-0] Error: Expect $(`//div[@id="d1"]`) to have class
[chrome 122.0.6261.128 windows #0-0]
[chrome 122.0.6261.128 windows #0-0] Expected: StringContaining "clickable step"
[chrome 122.0.6261.128 windows #0-0] Received: "clickable step"
[chrome 122.0.6261.128 windows #0-0]     at Context.<anonymous> (file:///C:/work/wdio/test/specs/test.e2e.ts:20:27)
```

Here is an example: https://github.com/muhserks/wdio

**Comment by christian-bromann** [comment]
Hey @muhserks , thanks for raising the issue and providing a reproducible example!

I looked into it and it seems your test fails in this line: `await expect(div).toHaveElementClass('clickable step');`. The reason is that `toHaveElementClass` expects a single class name and not multiple. Changing the test to:

```ts
it('Multiplice classes 1', async () => {
    const div = await $('//div[@id="d1"]');
    await expect(div).toHaveElementClass('clickable');
    await expect(div).toHaveElementClass('step');
});
```

Will make the test run work. This is definitely a problem of documentation. It should be more clear that only one class name is expected. I am happy to extend the functionality to take an array of class names.

Any contributions that improve this behavior or the docs would be appreciated.
