### ISSUE TITLE
[🐛 Bug]: Getting "el.getText is not a function" error when calling "toHaveText" on element arrays

### ISSUE THREAD

**Issue by cchangenot** [webdriverio/expect-webdriverio#1555]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.37.0

### Node.js Version

20.11.1

### Mode

Standalone Mode

### What happened?

Trying to upgrade from 8.32.4 to 8.37.0, I get tests failures when they are using `toHaveText` expectation on element arrays.
Seems be occuring since the 8.34.1 version.

### How to reproduce the bug.

- Getting `el.getText is not a function` :
```ts
describe("toHaveText", () => {
  it("should work with element arrays", async () => {
    await browser.url("https://webdriver.io/");
    await expect($$(".hero .container a.button")).toHaveText(["Get Started", "Why WebdriverIO?", "View on GitHub", "Watch on YouTube"]);
  });
});
```

- As a workaround using something like this, this works:
```ts
await expect($$(".hero .container a.button")).toBeElementsArrayOfSize(4);
await expect($$(".hero .container a.button"))[0]).toHaveText("Get Started");
await expect($$(".hero .container a.button"))[1]).toHaveText("Why WebdriverIO?");
```

### Relevant log output

```typescript
TypeError: el.getText is not a function
    at async UserContext.<anonymous>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by RodrigoGambino** [comment]
Hi, I have the same error in toHaveText but using `expect.stringContaining`, for example:

`await expect(currentalias).not.toHaveText(expect.stringContaining(previousalias)); `

currentalias and previousalias are string, but it gives me the error `el.getText is not a function`. 

I have version 8.39.1 of webdriverio

**Comment by RodrigoGambino** [comment]
@christian-bromann Hi, I have the same error in toHaveText but using expect.stringContaining, for example:

`
```typescript
const string1 = "Hello World";
const string2 = "Bye";
await expect(string1).not.toHaveText(expect.stringContaining(string2));
``` `

gives me the error el.getText is not a function.

I have version 8.39.1 of webdriverio

**Comment by christian-bromann** [comment]
As mentioned in the other issue please get involved help the project resolve the bug. WebdriverIO has a stipend program so you will receive cash doing so! This project is not run only by me but is a community first project.

**Comment by lacell75** [comment]
@RodrigoGambino toHaveText API is a element or browser matcher, not a string matcher. So the error `el.getText is not a function` is normal. I think close this issue because the issue reported by @cchangenot has been correctly fixed.

**Comment by christian-bromann** [comment]
Thanks for clarifying @lacell75
