### ISSUE TITLE
Populate missing element items to `WebdriverIO.ElementArray` when using `toBeElementsArrayOfSize`

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/expect-webdriverio#1616]
Given the following situation:

```ts
    const loads = await $('#output').$$('li');
    await expect(loads).toBeElementsArrayOfSize(9);

    loads = await $('#output').$$('li'); // <-- need to add this to make it work

    await expect(loads[0]).toHaveText('lifecycle-update-a componentWillLoad');
    await expect(loads[1]).toHaveText('lifecycle-update-a componentDidLoad');
    await expect(loads[2]).toHaveText('async add child components to lifecycle-update-a 1');
    await expect(loads[3]).toHaveText('lifecycle-update-a componentWillUpdate 1');
    await expect(loads[4]).toHaveText('lifecycle-update-b componentWillLoad 1');
    await expect(loads[5]).toHaveText('lifecycle-update-c componentWillLoad 1');
    await expect(loads[6]).toHaveText('lifecycle-update-c componentDidLoad 1');
    await expect(loads[7]).toHaveText('lifecycle-update-b componentDidLoad 1');
    await expect(loads[8]).toHaveText('lifecycle-update-a componentDidUpdate 1');
```

The `toBeElementsArrayOfSize` matcher will wait until the size of the element query will match the expected value. As a user you would think that the `loads` element array now contains `9` elements. This is a false assumption though. If you define an element, it will contain the amount of elements it found at the time the variable was defined, even though through the passing expectation, the state has changed.

### Proposal

It would be nice if the `toBeElementsArrayOfSize` would update the passed in element array so that the user can continue their tests without having to refetch the elements.

**Comment by mathew-jithin** [comment]
@christian-bromann Added a few changes as per the proposal. Can you please have a check?

https://github.com/webdriverio/expect-webdriverio/pull/1665

**Comment by christian-bromann** [comment]
Thanks so much for tackling this!
