### ISSUE TITLE
Getting, TypeError: (0 , _expectBundle.EXPECTED_COLOR) is not a function

### ISSUE THREAD

**Issue by Deepa815** [webdriverio/expect-webdriverio#1671]
I am new to automation. I am getting the error (TypeError: (0 , _expectBundle.EXPECTED_COLOR) is not a function) when i pass variable from pages to test.

_could anyone please help me with it_

**Code in Page:**
import { type Locator, type Page } from '@playwright/test'
export let cnt;

//Class 
export class Projmngcls {
    readonly PFURL: Page;
    readonly dshbrd: Locator;

    constructor(PFURL: Page) {
            this.PFURL = PFURL; //Site
           this.dshbrd = PFURL.getByRole('link', { name: 'dashboard Dashboard' });

async cmp(cnt: string) {
        cnt = '02';
        //strcnt = 'Users'
        await this.dshbrd.click();
  }
}
**Code in Tests:**
import { test, expect } from '@playwright/test';
import { Projmngcls,cnt } from './Pages/PM'
test('PM', async ({ page }) => {
    const PMvrfy = new Projmngcls(page);
    await PMvrfy.cmp(cnt);
     **await expect(PMvrfy.dshbrdusrcnt).toHaveText(cnt);**
});

**Comment by christian-bromann** [comment]
Hey @Deepa815 👋 it seems you are using Playwright, not WebdriverIO. Please raise this issue in the Playwright project. Thank you!
