### ISSUE TITLE
toBeElementsArrayOfSize seems to alter the array it's check for a moment

### ISSUE THREAD

**Issue by brickfungus** [webdriverio/expect-webdriverio#1679]
```typescript
await browser.url("https://the-internet.herokuapp.com/checkboxes");
const checkboxes = await $$('input[type="checkbox"]').getElements();
console.log(`Length before: ${checkboxes.length}`);
await expect(checkboxes).toBeElementsArrayOfSize(2);
const firstCheckbox = checkboxes[0];
console.log(`Length after: ${checkboxes.length}`);
await browser.pause(2000);
console.log(`Length after a pause: ${checkboxes.length}`);
await expect(checkboxes).toBeElementsArrayOfSize(2);
console.log(`Checkbox: ${firstCheckbox}`);
try {
    await firstCheckbox.click();
} catch (e) {
    console.error(`can't click ${e}`);
}
```

Output
```bash
[0-0] Length before: 2
[0-0] Length after: 0
[0-0] Length after a pause: 0
[0-0] Checkbox: undefined
[0-0] can't click TypeError: Cannot read properties of undefined (reading 'click')
```

I'm assuming this is an expect-webdriverio thing and not a @wdio thing

**Comment by christian-bromann** [comment]
@brickfungus can you verify you are using the latest version? Also can you provide a reproducible example?

**Comment by brickfungus** [comment]
Yes i'm on latest version of all, and i posted an example in the original post

**Comment by christian-bromann** [comment]
@mathew-jithin mind taking a look, I think this is related to your recent change.

**Comment by mathew-jithin** [comment]
Hi @christian-bromann Let me have a check on this today.

**Comment by brickfungus** [comment]
i mean... i guess the updated instructions
`**Note:** This matcher will update the passed array with the latest elements if the assertion passes. However, if you've reassigned the variable, you'll need to fetch the elements again.`
says it.  Feel like this should've been a major release then, since this broke tests for us

**Comment by mathew-jithin** [comment]
@brickfungus Yes, this was the change done in the previous PR.

@christian-bromann Can you please help me with a suggestion on the expected workflow to be changed to? Will do accordingly.

**Comment by christian-bromann** [comment]
I am particularly concerned about this part:

```ts
await browser.url("https://the-internet.herokuapp.com/checkboxes");
const checkboxes = await $$('input[type="checkbox"]').getElements();
console.log(`Length before: ${checkboxes.length}`);
await expect(checkboxes).toBeElementsArrayOfSize(2);
const firstCheckbox = checkboxes[0];
```

which logs: 

```
[0-0] Length before: 2
[0-0] Length after: 0
```

The `await expect(checkboxes).toBeElementsArrayOfSize(2);` assertion should not remove the items of the array, instead it should add them when they were 0 before.

**Comment by mathew-jithin** [comment]
Sure. Let me check on this and see what happened.

**Comment by brickfungus** [comment]
Any progress on this?  I'm having to rewrite a lot of tests to accommodate this

**Comment by brickfungus** [comment]
![image](https://github.com/user-attachments/assets/0405b2c6-aee6-4181-835e-6df849939035)
was playing around with it, and this fixed it, but it's ugly.  at the end of the day, we need to deepclone the passed in check, because when the length gets set to zero, it deletes the array

**Comment by christian-bromann** [comment]
@brickfungus see the "help wanted" label, any contributions are welcome!

**Comment by brickfungus** [comment]
I think I figured it out.  Will have a PR soon

**Comment by mathew-jithin** [comment]
Sorry guys for the messup. I am actually travelling and is away from my
laptop, so was not able to make the change. Thanks a lot 🥲

Best Regards,
Jithin Mathew
Connect with me on LinkedIn <https://in.linkedin.com/in/mathewjithin>
