### ISSUE TITLE
Do not output `Warning! Unsupported expect lib is used` to console

### ISSUE THREAD

**Issue by vgrigoruk** [webdriverio/expect-webdriverio#182]
I've upgraded `webdriverio` & all used `@wdio/*` package dependencies to v6 on a projects which also uses `chai` for `expect(...)` matchers. Now, when I run tests, I see the following in STDOUT for each spec file that is executed:

```
[0-0] Warning! Unsupported expect lib is used.
  | Only Jasmine >= 3.3.0 and Jest's expect are supported.
  | expect-webdriverio is assigned to global.expectWdio
```
I was first confused to see this, as I don't have `expect-webdriverio` defined as a dependency in `package.json`. But then I noticed it is enabled by default now if you use `@wdio/mocha-framework` (https://github.com/webdriverio/webdriverio/pull/5335).

So, is there any way to suppress the warning?

**Comment by christian-bromann** [comment]
See https://github.com/webdriverio/expect-webdriverio/blob/21d261f861e9ae5653e187e0d0987e4c4b3c1e93/src/addMatchers.ts#L28-L36 .. I don't think there is a chance to suppress this. I suggest to introduce an environment variable to suppress the warning and mention that environment in there.

I also would recommend to replace chai with `expect-webdriverio` 😉

**Comment by vgrigoruk** [comment]
Although I really like `expect-webdriverio`, replacing `chai` with it doesn't sound like a viable solution for me at the moment (we've developed an internal library of chai matchers specifically for webdriverio browser tests, which are used in every single spec).

**Comment by Xotabu4** [comment]
I think there might be good idea to have config key for such cases like
```
/**
* Enable expect-webdriverio matchers
* default: true
*/
enableExpectWebdriverioMatchers: false
```

**Comment by mgrybyk** [comment]
@vgrigoruk @Xotabu4 feel free to raise a PR to webdriverio to add the config key.
Might be easier to add `disableExpectWebdriverio` just not to mess up with the default values.
It should be done for all 3 test frameworks https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-mocha-framework/src/index.js#L95

Alternatively, we can add some env variable to suppress the message
