### ISSUE TITLE
expect should not be a required dependency

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/expect-webdriverio#198]
* `expect` is only required for `expect-webdriverio` to work with Mocha / CucumberJS test frameworks out of the box in `webdriverio`.
* `expect` is not a required dependency for `expect-webdriverio` used in the Jasmine framework.

Ideally, `expect-webdriverio` should install `expect` depending on if Jasmine/Jest installation however it's not currently possible.

**Comment by christian-bromann** [comment]
This got obsolete at this point as we don't support Jasmine matchers anymore.
