### ISSUE TITLE
toHaveValue in appium

### ISSUE THREAD

**Issue by ashwinjk** [webdriverio/expect-webdriverio#309]
When using appium for testing ios safari

```
       appiumVersion: '1.17.1',
        browserName: 'Safari',
        deviceName: 'iPhone XS Simulator',
        deviceOrientation: 'portrait',
        platformName: 'iOS',
        platformVersion: '13.0',
```

The following check fails

`expect($('#search')).toHaveValue('');`

with error 

`Method has not yet been implemented"`

and from appium log
```
Calling AppiumDriver.getProperty() with args: ["value","5011","9ee8f32f-9e8e-46c4-b488-e2c6dda4cf96"]
2020-12-29 21:34:01:303 - [debug] [XCUITest] Executing command 'getProperty'
```

However the same test passes when 

`expect($('#search')).toHaveAttribute('value', '');`

It seems to be related to the issue brought up here
https://github.com/webdriverio/webdriverio/pull/3606

**Comment by christian-bromann** [comment]
@ashwinjk you can't call this command with Appium as it is not supported in a native mobile context. It only works in a web context. I am not sure what you are trying to do but you should use a [command](https://webdriver.io/docs/api/appium.html) that is supported for this environment.

**Comment by ashwinjk** [comment]
@christian-bromann , let me explain. This is for testing a web page where a input box value is verified

this `expect($('#search')).toHaveValue('');` fails with error posted in the original description

this `expect($('#search')).toHaveAttribute('value', '');` passes OK

from the look of it, it seems to be very similar to the property vs attribute issue raised in webdriverio/webdriverio#3606

**Comment by christian-bromann** [comment]
I understand the issue. My statement is still valid. You can't call certain WebDriver commands in native mobile contexts. For example, there is no way to call the `execute` command because there is no JavaScript environment in a native mobile context you can inject JavaScript into. The same applies for the `getProperty` command.
