### ISSUE TITLE
Report assertions

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/expect-webdriverio#33]
In order to better understand what has been asserted it would be super helpful if the library could report every assertion so that the consumer (WebdriverIO) can use this to enrich its reporting capabilities.

**Comment by mgrybyk** [comment]
Can you please add some more details?

The assertion lib should send some event to the wdio reporter, then specific reporter (ex allure) can listen for such events and add assertions like steps?

**Comment by christian-bromann** [comment]
> The assertion lib should send some event to the wdio reporter, then specific reporter (ex allure) can listen for such events and add assertions like steps?

Correct. Maybe we can expose an eventlistener that allows reporter to receive assertion events and include them in their reports.
