### ISSUE TITLE
String option 'ignoreCase' not working for 'toHaveValue()'

### ISSUE THREAD

**Issue by AnnikaNissen** [webdriverio/expect-webdriverio#36]
Hi 

It seems like the option `ignoreCase` is not working for the `toHaveValue()` assertion method. 

Given this assertion:
```
expect(browser.$('#searchField')).toHaveValue('iPhone', {ignoreCase: true, asString: true});
```

I'm getting this error when running the test:
```
[chrome  mac os x #0-0] Error: Expect $(`#searchField`) to have property value
[chrome  mac os x #0-0]
[chrome  mac os x #0-0] Expected: "iPhone"
[chrome  mac os x #0-0] Received: "iphone"
```

Is that a bug or do the 'stringOptions' just don't work for `toHaveValue`?

Best regards,
Annika

By the way:  
Great project! I'm using 'chai-webdriverio' right now and just started to look into this - it looks very promising :)! I like the syntax and the fact that you can pass in WebdriverIO elements and not only selectors like in 'chai-webdriverio'.

**Comment by mgrybyk** [comment]
Might be a bug

**Comment by mgrybyk** [comment]
@AnnikaNissen thanks for submitting! Apparently not only `toHaveValue` function is affected.

**Comment by AnnikaNissen** [comment]
@mgrybyk You are welcome! Thanks for your great work, guys 😃 

Besides the `toHaveValue` function, I tested it with the `toHaveText` function and that worked as expected.

**Comment by christian-bromann** [comment]
This seems to be fixed on latest master.
