### ISSUE TITLE
expect(elem).toBeElementsArrayOfSize gte behaves as strict equals instead of greater than or equal

### ISSUE THREAD

**Issue by jamesmortensen** [webdriverio/expect-webdriverio#371]
```
   expect(sessionCountListBeforeCleanUp).toBeElementsArrayOfSize({ gte: 3 })
```

The above line, when checking that the array is greater or equal than 3, fails if it gets a number greater than 3.  In this example, our `sessionCountListBeforeCleanUp` variable is of size 4.

The below output seems to contradict itself, since a value of 4 is indeed greater than or equal to 4.  

```
Expect $$(`//div[@class="span6 class-timings-list"]/ul/li[@class="hasHoverStyles"]`) to be elements array of size

Expected: ">= 3"
Received: 4
[chrome 83.0.4103.61 linux #0-0] Error: Expect $$(`//div[@class="span6 class-timings-list"]/ul/li[@class="hasHoverStyles"]`) to be elements array of size
[chrome 83.0.4103.61 linux #0-0]
[chrome 83.0.4103.61 linux #0-0] Expected: ">= 3"
[chrome 83.0.4103.61 linux #0-0] Received: 4
[chrome 83.0.4103.61 linux #0-0]     at Context.<anonymous>
```

While we would love to have a strict equals version of this, the gte behavior does not seem correct.

Platform: Mac OS
WebdriverIO:  v7.0.7

**Comment by TuxedoFish** [comment]
I am working on this error 👍 : https://github.com/TuxedoFish/expect-webdriverio/tree/fix-number-comparison

Think there was some issues with how the matcher was working but I am trying to simplify the number comparison logic at the same time, to make it easier to add new matchers at the same time. For a strict equals I believe you can use "eq" or is it the lack of a ">" and "<" operator which would likely be "gt" and "lt" if added?

**Comment by christian-bromann** [comment]
@TuxedoFish thanks for helping fixing the issue, let's continue convo in the PR.
