### ISSUE TITLE
Deprecate old v5 commands

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/expect-webdriverio#392]
We still allow for `toBeVisible` and other v5 commands which should be deprecated.

**Comment by mathew-jithin** [comment]
@christian-bromann Can you please details what needs to be done here? Can pick this up.

**Comment by christian-bromann** [comment]
I think the only matchers are really just `toBeVisible`, `toBeVisibleInViewport`

**Comment by mathew-jithin** [comment]
@christian-bromann Made this change. Please review: https://github.com/webdriverio/expect-webdriverio/pull/433
