### ISSUE TITLE
Allow text options for `toHaveText` or `toHaveTextContaining`

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/expect-webdriverio#397]
I just ran into the following error message:

```
Expect $(`.todo`) to have text

Expected: "ToDo #3"
Received: " ToDo #3  "
```

I suggest to allow options for `toHaveText` and `toHaveTextContaining` to strip text from the result. These options should be default `true` as I believe there are more scenarios where you want to strip it rather than keep it.

**Comment by mathew-jithin** [comment]
@christian-bromann Please have a check:

https://github.com/webdriverio/expect-webdriverio/pull/398

**Comment by christian-bromann** [comment]
Thanks for taking a stab at it, let's continue convo in the PR.
