### ISSUE TITLE
toHaveAttribute type checking

### ISSUE THREAD

**Issue by Harry-Liversedge** [webdriverio/expect-webdriverio#438]
Inside of toHaveAttribute the condition is:

```
async function condition(el: WebdriverIO.Element, attribute: string, value: string, options: ExpectWebdriverIO.StringOptions): Promise<any> {
    const attr = await el.getAttribute(attribute)
    if (typeof attr !== 'string') {
        return { result: false, value: attr }
    }

    if (typeof value !== 'string') {
        return { result: true, value: attr }
    }

    return compareText(attr, value, options)
}
```

Which means that a test like this would pass

```
test('success with non-string attribute value as expected', async () => {
        el.getAttribute = jest.fn().mockImplementation((attribute: string) => {
            return "Correct Value"
        })
        const result = await toHaveAttribute(el, "attribute_name", 123, { ignoreCase: true });
        expect(result.pass).toBe(true)
    })
```

Is this the expected behaviour because surely this implies that passing in any non-string value as the expected would result in a success which seems like confusing behaviour to me?

**Comment by christian-bromann** [comment]
@Harry-Liversedge I believe the reason for this is to allow assertions of flag attributes, e.g.:

```html
<div data-hasFlag>...</div>
```
so that the following can done:
```js
expect(elem).toHavAttribute("data-hasFlag")
```
You are right though that it is not the intention to have something pass the assertion just because it is not a string. I am sure we can be more strict here. Any contributions are welcome!

**Comment by Harry-Liversedge** [comment]
@christian-bromann Ahh I see that makes sense now, I was trying to write some tests for toHaveAttribute and spotted this. Realized there is quite a few test files to write so I might separate that out and make a new branch with just tests for toHaveAttribute and add this check.

I am thinking it should only return true if the second argument is not present? Think can be stricter on the inputs to the function I'll take a look 👍
