### ISSUE TITLE
Assertions are thrown twice 

### ISSUE THREAD

**Issue by praveendvd** [webdriverio/expect-webdriverio#462]
**In jasmine framework this throws two assertions :**

```
it('Sorts the inventory in asc order of price and adds element to cart', async () => {
    expect(1).toBe(2)
});

```

**This can be validated by :**

**Adding below to config file:**

```
    jasmineOpts: {
        // Jasmine default timeout
        defaultTimeoutInterval: 60000,
        //
        // The Jasmine framework allows interception of each assertion in order to log the state of the application
        // or website depending on the result. For example, it is pretty handy to take a screenshot every time
        // an assertion fails.
        expectationResultHandler: function (passed, assertion) {

            console.log("Pass:      ",passed,"Assertion:          ", assertion)
            // do something
        }
    },
```

**This gives below outputs:**

```

[0-0] Pass:       false Assertion:           {
[0-0]   matcherName: 'toBe',
[0-0]   passed: false,
[0-0]   message: 'Expected 1 to be 2.',
[0-0]   error: undefined,
[0-0]   errorForStack: undefined,
[0-0]   actual: 1,
[0-0]   expected: 2
[0-0] }
[0-0] Pass:       false Assertion:           {
[0-0]   matcherName: '',
[0-0]   passed: false,
[0-0]   expected: '',
[0-0]   actual: '',
[0-0]   error: {
[0-0]     matcherName: 'toBe',
[0-0]     message: 'Expected 1 to be 2.',
[0-0]     stack: 'Error: Expected 1 to be 2.\n' +
[0-0]       '    at <Jasmine>\n' +
[0-0]       '    at Spec.addExpectationResult (D:\\prject\\node_modules\\@wdio\\jasmine-framework\\build\\index.js:296:32)\n' +
[0-0]       '    at <Jasmine>\n' +
[0-0]       '    at UserContext.<anonymous> (D:\\prject\\test\\specs\\cartFeature.js:12:25)\n' +
[0-0]       '    at UserContext.executeAsync (D:\\prject\\node_modules\\@wdio\\utils\\build\\shim.js:136:25)',
[0-0]     passed: false,
[0-0]     expected: 2,
[0-0]     actual: 1
[0-0]   }
[0-0] }

```
**And the allure report looks like:**

![image](https://user-images.githubusercontent.com/45095911/121040323-b8471a00-c7a9-11eb-9c33-2d28191770c1.png)

**Do anyone knows how to avoid this ?**

**Reproducible example:**

[webdriverio-Jasmine - Copy.zip](https://github.com/webdriverio/expect-webdriverio/files/6610112/webdriverio-Jasmine.-.Copy.zip)

**Just run:**

```
npm install
npx wdio
./openAllureRport.bat

```

observe console log and allure report as mentioned above

**Comment by christian-bromann** [comment]
This error might also be related to the Allure reporter specifically. Anyway any contribution to this is welcome and appreciated.

**Comment by praveendvd** [comment]
> This error might also be related to the Allure reporter specifically. Anyway any contribution to this is welcome and appreciated.

I think this is caused due to the enhanceMessage method that adds more descripte error and throws the error again

**Comment by praveendvd** [comment]
issues was due to error in one of the import in config , closing the issue

**Comment by praveendvd** [comment]
@christian-bromann could you please help me out to know how to install this library from source , 

Nom build is giving me error like statement is expected .

Could you let me know the order in which the npm scripts  commands needs to be executed?

**Comment by christian-bromann** [comment]
Please check out our [contribution guidelines](https://webdriver.io/docs/contribute) for the main WebdriverIO project.

**Comment by praveendvd** [comment]
@christian-bromann 

![image](https://user-images.githubusercontent.com/45095911/122588977-9c6c2f80-d057-11eb-8f5e-9c3a2b5bea5e.png)


Removing this line  from jasmine.js  fixes the issue ,

**Comment by praveendvd** [comment]
this is inside jasmine-core/jasmine , is it core jasmine file or webdriverio plugin

**Comment by praveendvd** [comment]
![image](https://user-images.githubusercontent.com/45095911/122589962-d12cb680-d058-11eb-9417-87641cb9d1b0.png)

**Comment by praveendvd** [comment]
@christian-bromann  I have created a pull request for this , thank you ☺️
