### ISSUE TITLE
expect-webdriverio and webdriverio with typescript = > Unexpected return from a matcher function.

### ISSUE THREAD

**Issue by mctrafik** [webdriverio/expect-webdriverio#62]
Good day.

I have no idea where things are failing, but I'm unable to use expect assertions.

My packages:

```
"@types/chromedriver": "^81.0.0",
"@types/jest": "23.3.13",
"@types/node": "^10.17.21",
"chromedriver": "^81.0.0",
"expect-webdriverio": "^1.1.0",
"jest": "22.4.3",
"ts-jest": "^22.4.6",
"webdriverio": "5.22.4"
```

I'm using jest and typescript. In my tsconfig:

```
"compilerOptions": {
    "module": "commonjs",
    "types": [
      "node",
      "jest", 
      "webdriverio",
      "expect-webdriverio"
    ],
}
```

And in my jestconfig:

```
  testEnvironment: 'node',
  setupTestFrameworkScriptFile: 'expect-webdriverio',
  transform: {
    "^.+\\.tsx?$": "ts-jest",
  },
```

My test code contains:

```typescript
 const el = await browser.$('input');
 await el.click();
 expect(el).toBeFocused();
```

And this fails!

Error:

```
    Unexpected return from a matcher function.
    Matcher functions should return an object in the following format:
      {message?: string | function, pass: boolean}
    '{}' was returned

      83 |   await el.click();
    > 84 |    expect(el).toBeFocused();

     
      at _validateResult (node_modules/expect/build/index.js:196:11)
      at Object.throwingMatcher [as toBeFocused] (node_modules/expect/build/index.js:158:5)
      at src/my/test/file.ts

```

What's happening here and how do I fix it?

**Comment by christian-bromann** [comment]
Have you tried:

```
await expect(el).toBeFocused()
```

**Comment by mctrafik** [comment]
I tried as a sanity check, but it doesn't and shouldn't help at all.
Function toBeFocused() has an "undefined" return type. And event if it was a Promise, the error happens before toBeFocused() has a chance to return anything.

**Comment by mgrybyk** [comment]
@mctrafik can you please update to the latest version 1.1.5 ?

**Comment by mgrybyk** [comment]
![image](https://user-images.githubusercontent.com/25589559/80522070-3ffa0c80-898c-11ea-9b8d-6f210f8b3c3a.png)

**Comment by mctrafik** [comment]
Updated to 1.1.5 Same issue. :( 

@mgrybyk Can you tell me which wdio and jest versions you used?

**Comment by mctrafik** [comment]
My code base is on jest 22. I know we couldn't upgrade to 25, but I tried 23.6.0 and it works now. 

Maybe you can list in the readme that Jest@^23 is required?

**Comment by mgrybyk** [comment]
@mctrafik will do, thank you!
