### ISSUE TITLE
Compilation error for ExpectWebdriverIO.Expect and jest.Expect

### ISSUE THREAD

**Issue by vaibhavjagdale** [webdriverio/expect-webdriverio#689]
I am working on UI and API test framework. where I have used expect from expect-webdriverio for UI validations and expect from chai for api validations.

when I run tsc, I will get below errors.

`node_modules/@types/jest/index.d.ts:47:15 - error TS2451: Cannot redeclare block-scoped variable 'expect'.
47 declare const expect: jest.Expect;
node_modules/expect-webdriverio/types/jest-global.d.ts:3:15
3 declare const expect: ExpectWebdriverIO.Expect
'expect' was also declared here.
node_modules/expect-webdriverio/types/jest-global.d.ts:3:15 - error TS2451: Cannot redeclare block-scoped variable 'expect'.
3 declare const expect: ExpectWebdriverIO.Expect
node_modules/@types/jest/index.d.ts:47:15
47 declare const expect: jest.Expect;
 'expect' was also declared here.`

I am not sure but its types error.
**tsconfig.json**
![image](https://user-images.githubusercontent.com/50039131/156161161-c17ebaad-4199-4d5a-af6e-b880289ccd79.png)

**Does expect-webdriverio build on top of jest and creating types issue ?**
node_modules/expect-webdriverio/types/jest-global.d.ts
![image](https://user-images.githubusercontent.com/50039131/156161510-8d986a33-3961-4133-8b0b-a9c76f605c8c.png)

**Comment by christian-bromann** [comment]
If you use Jest please setup your types according to the [docs](https://github.com/webdriverio/expect-webdriverio/blob/main/docs/Types.md) as `expect-webdriverio/jest`. Let me know if that works.
