### ISSUE TITLE
Failed tests does not exit

### ISSUE THREAD

**Issue by Geloloboy** [webdriverio/expect-webdriverio#7]
Description:
When a tests fail, it doesn't exit automatically

Expected Behaviour:
When tests fail, it'll continue running and exit properly

Actual Behaviour:
When tests fail, it gets stuck to the point where it describes the discrepancy between the expected and actual results

Additional Info:
I'm using mocha as my framework

**Comment by christian-bromann** [comment]
@Geloloboy depends on how you have setup Mocha to work it usually doesn't exist after a failure. See Mochas `bail` option.

**Comment by Geloloboy** [comment]
@christian-bromann 
I tried adding `bail` to my mochaopts but it didn't help. Here's what my mochaOpts look like:
`
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000,
        require: ['@babel/register'],
        bail: true
    },
`

Also, this doesn't happen when I was using the Chai assertion library.

**Comment by mgrybyk** [comment]
@Geloloboy can you please help reproducing the issue?

May you share your wdio conf and minimal reproducible example?

Also make sure you have latest versions of webdriverio and all wdio packages.

**Comment by Geloloboy** [comment]
@mgrybyk 
I was able to replicate this issue using this repo:
https://github.com/Geloloboy/wdioexpectissue.git

Looks like the problem appears when you add allure as a reporter

**Comment by sergiocabreraoriaret** [comment]
I agree with @Geloloboy  ... for me, this is reproducible if in the wdio config has allure & mochaweosme at the same time.

If only has mochawesome,... works fine

![image](https://user-images.githubusercontent.com/58176975/73835810-53bf2800-480e-11ea-8aa8-29b7d1bb50d7.png)

**Comment by mgrybyk** [comment]
@sergiocabreraoriaret can you please try in the latest version? I guess the issue has been fixed

**Comment by PavithraRavichandran** [comment]
I face this issue when I use the chai assert in the end of my test and assert fails. When I write test as a positive one, then my test exists. 
mochaOpts: {
        ui: 'bdd',
        require : ['@babel/register'],
        timeout: 60000
    },
