### ISSUE TITLE
Broken links: Element matchers linking to underlying functions

### ISSUE THREAD

**Issue by maikeru** [webdriverio/expect-webdriverio#711]
Steps to reproduce:
1. In a browser visit https://webdriver.io/docs/api/expect-webdriverio#element-matchers
2. Click on the `isDisplayed` link under `toBeDisplayed`

Expected behaviour:
The doc page for `isDisplayed` should load.

Actual behaviour:
A Github 404 page is displayed.

From what I can see the broken link is pointing at 
https://github.com/webdriverio/expect-webdriverio/blob/main/docs/api/element/isDisplayed.html

when it should be pointing at
https://webdriver.io/docs/api/element/isDisplayed/

I tried a few other links on the page and they seem to have the same problem.

**Comment by maikeru** [comment]
Had a go at a quick fix https://github.com/webdriverio/expect-webdriverio/pull/712

**Comment by maikeru** [comment]
@christian-bromann did you get a chance to re-deploy the website? I'm still seeing the old (github) links

**Comment by christian-bromann** [comment]
Not yet, let me trigger the workflow!
