### ISSUE TITLE
error TS1128: Declaration or statement expected.

### ISSUE THREAD

**Issue by pillsilly** [webdriverio/expect-webdriverio#723]
I'm trying to make a code change but when I set up the project

When I try to build it:
` npx tsc --build tsconfig.build.json`

```
1 ../../types/expect-webdriverio.d.ts
  ~

```
![image](https://user-images.githubusercontent.com/13218151/163298936-37d04aa1-ef43-4d0f-978d-c7f3288c6088.png)

Anyone has idea what cause it?

**Comment by pillsilly** [comment]
@mgrybyk

**Comment by mgrybyk** [comment]
You might be using incompatible typescript version or some issues with tsconfig.

**Comment by pillsilly** [comment]
thank you ! I used `npm ci` this to go get a cleaner TS version so building came normal
@mgrybyk

**Comment by pillsilly** [comment]
> thank you ! I used `npm ci` this time to get a cleaner TS version building process came normal. @mgrybyk

Strangely, when I later on tried to work on my the other computer, the problem could not be resolved by either varies ways of `npm ci`, `npm install` ...

Also, I found https://github.com/webdriverio/expect-webdriverio/issues/690  
which seemed to be the same issue.

Thus I had to reopen this issue @mgrybyk ...

**Comment by pillsilly** [comment]
And provided a fix

**Comment by pillsilly** [comment]
Root cause clear now

![image](https://user-images.githubusercontent.com/13218151/164480948-954955f9-d50b-49af-befa-dd607c461b0f.png)

It is the soft link not recognized by Windows file system ..

And previously though I test in WSL but the clone operation was done in windows.

ONLY when clone operation is done in Linux the file could be correctly soft linked 

So for whoever use windows it could be headache...

This is also the answer of https://github.com/webdriverio/expect-webdriverio/issues/690

Though I think it's a bit not-friendly to windows users but currently I need to work on the other fix (which is the actual one I was heading to work on😆)

but at least I think and hope this answer could somehow help the other windows users in some degree
