### ISSUE TITLE
expect(---).toHaveValue(---) trims the input by default

### ISSUE THREAD

**Issue by alminv** [webdriverio/expect-webdriverio#894]
Environment:

    WebdriverIO version: 7.24.1
    Node.js version: 16.17.1
    Browser name and version: Chrome 106
    Platform name and version: Windows 10
    
Describe the bug
If text in the field starts or ends with a space or new line/paragraph except(field).toHaveValue(value) fails because text is trimmed by default.

To Reproduce
`const field = await $"someField";   
const text = "Some text ";
await field.setValue(text);
await expect(field).toHaveValue(text);
`

Expected behavior
Test pass without issues.

Actual behavior
Test fail with: Expected: "Some text "; Received: "Some text"

Notes

- expect(field).toHaveValue(text, { trim: false }) works fine
- this is a change in behavior from older WebdriverIO versions like 6.x

**Comment by christian-bromann** [comment]
Trimming is the default behavior, if you like to change that you can do this:

```js
import { setDefaultOptions } from 'expect-webdriverio'
setDefaultOptions({ trim: false })
```

Closing as I don't see a bug here. Correct me if I am wrong.
