### ISSUE TITLE
Make `expect-webdriverio` independent from global WebdriverIO primitives (support for it in standalone mode)

### ISSUE THREAD

**Issue by DudaGod** [webdriverio/expect-webdriverio#924]
Hello. I faced with problem when try to use expect-webdriverio@3.4.0 in my standalone script. Example of script to reproduce a problem:
```
const wdio = require('webdriverio');
const {setOptions} = require('expect-webdriverio');

setOptions({wait: 5000, interval: 100});

let browser;
const opts = {
    protocol: 'http',
    hostname: 'localhost',
    port: 4444,
    path: '/wd/hub',
    automationProtocol: 'devtools',

    capabilities: {
        browserName: 'chrome',
    }
};

(async function () {
    browser = await wdio.remote(opts);

    await browser.url('https://webdriver.io/');
    await expect(browser).toHaveUrl('https://foo.io');

    await browser.deleteSession();
})()
    .catch(async (e) => {
        console.error('ERROR:', e);
        await browser.deleteSession();
    })
```

When I run this script I get the following error:
```
JestAssertionError: Expect window to have url

Expected: "https://foo.io"
Received: undefined
    at /Users/dudkevich/job/projects/dudkevich-scripts/HERMIONE-694.hermione_expect/wdio.js:27:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  matcherResult: {
    pass: false,
    message: 'Expect window to have url\n' +
      '\n' +
      'Expected: \u001b[32m"https://foo.io"\u001b[39m\n' +
      'Received: \u001b[31mundefined\u001b[39m'
  }
}
```

During the debugging process, I found that the problem is that in this piece of code - https://github.com/webdriverio/expect-webdriverio/blob/v3.4.0/src/utils.ts#L30. Instance of browser use here from global and does not passed through arguments of `waitUntil` helper.

Can I fix it and send PR with pass `browser` instance to this helper through arguments? Or version 3 is no longer supported and all changes need to be done only in version 4 which is now in beta?

**Comment by christian-bromann** [comment]
I am happy to create a `v3` branch and continue releases for it but ultimately with `v8` we will move forward with version 4 so we would need to have two PRs.

**Comment by DudaGod** [comment]
> I am happy to create a v3 branch and continue releases for it but ultimately with v8 we will move forward with version 4 so we would need to have two PRs.

In v4 used [@wdio/globals](https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-globals) - https://github.com/webdriverio/expect-webdriverio/blob/main/src/utils.ts#L1 which works only with wdio-runner (here - https://github.com/webdriverio/webdriverio/blob/428a9d729ae6231968a60908732fa3f607d195e9/packages/wdio-runner/src/index.ts#L300). So how it was supposed to be used in standalone script? Now it looks like with version 4 I have to require @wdio/globals and use its API to set `browser` to global, doesn't look very comfortable...

In v3 I will send a PR with fix.

**Comment by christian-bromann** [comment]
`expect-webdriverio` was developed to be used with the testrunner. I like the idea of making it independent of it and I think it should work similarly to how it will be implemented in v3.

**Comment by christian-bromann** [comment]
Actually I will pick this up for `v8` as it causes issues with the main repo.

**Comment by christian-bromann** [comment]
@DudaGod I fixed the issue in the `main` branch. You can adopt the same changes to the [`v3`](https://github.com/webdriverio/expect-webdriverio/tree/v3) branch and make a PR. I am happy to merge and release that one.

**Comment by DudaGod** [comment]
> @DudaGod I fixed the issue in the main branch. You can adopt the same changes to the [v3](https://github.com/webdriverio/expect-webdriverio/tree/v3) branch and make a PR. I am happy to merge and release that one.

Done - https://github.com/webdriverio/expect-webdriverio/pull/925
