### ISSUE TITLE
can we use or override Jasmine expect in cucumber project?

### ISSUE THREAD

**Issue by rajivnw** [webdriverio/expect-webdriverio#955]
I would like to use Jasmine expect in cucumber project. Reason is, I created test using webdriverio and cucumber project. WebDriverIo have its own expect but that stop the test execution once it fail (hard-assert). I would like to run all the steps and fail at the end (soft-assert).

I would like to override or would like to use Jasmine
instead of WebDriverIO assert https://webdriver.io/docs/assertion

**Comment by christian-bromann** [comment]
@rajivnw thanks for raising the issue.

Using Jasmine assertion library in a Cucumber project is currently not possible. There is currently an open issue to add [soft assertions](https://github.com/webdriverio/expect-webdriverio/issues/227) for `expect-webdriverio`. Please get involved you have interest in this. See also discussions in facebook/jest#13205.

Closing as duplicate if #227
