### ISSUE TITLE
[🐛 Bug]: @wdio v8 seems to break `jasmine.objectContaining` usages

### ISSUE THREAD

**Issue by BenoitZugmeyer** [webdriverio/expect-webdriverio#987]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.13

### Node.js Version

16.13.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
      maxInstances: 5,
      browserName: "chrome",
      acceptInsecureCerts: true,
    },
```

### What happened?

We are trying to upgrade [our project](https://github.com/DataDog/browser-sdk/) from `@wdio` v7 to v8. We are using the testrunner [with Jasmine](https://webdriver.io/docs/frameworks#using-jasmine).

Sadly, v8 seems to break compatibility with Jasmine anymore as some of our tests are failing with the error:

```
TypeError: Cannot read properties of undefined (reading 'equals')
```

It appears that it happens when using [jasmine.objectContaining()](https://jasmine.github.io/api/4.5/jasmine.html#.objectContaining).

### What is your expected behavior?

@wdio is compatible with jasmine and supports usages of `jasmine.objectContaining()`

### How to reproduce the bug.

See gist: https://gist.github.com/BenoitZugmeyer/1a76c6da7fab853ff3a332bc084bc164

```
git clone https://gist.github.com/BenoitZugmeyer/1a76c6da7fab853ff3a332bc084bc164 wdio-jasmine-issue
cd wdio-jasmine-issue
npm i
npm run wdio
```

### Relevant log output

```typescript
[chrome 108.0.5359.124 mac os x #0-0] 1) foo bar
[chrome 108.0.5359.124 mac os x #0-0] TypeError: Cannot read properties of undefined (reading 'equals')
[chrome 108.0.5359.124 mac os x #0-0]     at UserContext.<anonymous> (/.../wdio-jasmine-issue/test.e2e.js:5:8)
[chrome 108.0.5359.124 mac os x #0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for filing the issue!

In `v8` we have simplified the assertion library and removed integrated support for Jest and Jasmine for maintainability purposes. Now that we dropped sync support I wonder if providing support for Jasmine is that difficult. Any contributions that re-enable support would be appreciated.

**Comment by praveendvd** [comment]
@BenoitZugmeyer  replacing jasmine.objectContaining to expect.objectCOntaining works ,

**Comment by BenoitZugmeyer** [comment]
This is not jasmine though. I don't think mixing two assertion libraries and use one method or the other until it works is a satisfactory solution.

**Comment by praveendvd** [comment]
@BenoitZugmeyer expect extends jasmine so using jasmine with expect seems to be more of missing up libraries 

In the before hook , setting jasmine.objectContaining =  expet.objectContaining also seeems to fix the issue (or global.jasmine.objectContaining) . @christian-bromann  any thoungs

**Comment by christian-bromann** [comment]
As mentioned above, we can work on re-establishing the integration of `expect-webdriverio` and Jasmine. @BenoitZugmeyer if you like to only use the Jasmine assertion library, we recommend to set `injectGlobals` to `false`. In this case the global `expect` function will come from Jasmine.

**Comment by BenoitZugmeyer** [comment]
Thank you @christian-bromann, we'll definitly try that!

**Comment by praveendvd** [comment]
@christian-bromann should we set a flag just to override whether to use jasmine or edio expect. setting injectGlobal to false just for expect looks like an expensive operation . 

I can see that this setGlobal being done at two places : 

https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-jasmine-framework/src/index.ts#L201

https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-runner/src/index.ts#L287

**Comment by christian-bromann** [comment]
> remove this from this package ? and do only in the runner ?

We have to do it in the Jasmine package too because Jasmine registers `expect` as global by default. One improvement I could see is we could move it all into the runner and call [`noGlobals`](https://jasmine.github.io/tutorials/use_without_globals) in the jasmine package. Generally would like that folks by default use the wdio expect lib but as mentioned above I would be also interested just getting it back integrated into this library.

**Comment by brandan-schmitz** [comment]
Just wondering if there has been any work done on this? Having to set injectGlobals and then manually importing needed things on every spec is rather intensive of a process for larger applications with hundreds of tests.

**Comment by christian-bromann** [comment]
> Just wondering if there has been any work done on this?

Nothing has been reported here, you like to pick this up?

**Comment by christian-bromann** [comment]
With https://github.com/webdriverio/webdriverio/releases/tag/v8.11.2 we have re-enabled Jasmine assertions, therefore this is fixed. Please let me know if you still see an issue. Happy to re-open.
